<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>CRUD MVC Users</title>
    <link rel="stylesheet" href="assets/styles/css/style.css">
</head>
<body>
    <nav>
        <a href="index.php">Liste des utilisateurs</a>
        <a href="index.php?route=create_user">Ajouter un utilisateur</a>
    </nav>

    <main>
        <?php require $template; ?>
    </main>
</body>
</html>